--- #YAML:1.0
name:                Authen-CAS-Client
version:             0.02
abstract:            Provides an easy-to-use interface for authentication
license:             ~
generated_by:        ExtUtils::MakeMaker version 6.36
distribution_type:   module
requires:     
    LWP:                           0
    Test::MockObject:              0
    Test::More:                    0
    URI:                           0
    XML::LibXML:                   0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.2.html
    version: 1.2
author:
    - jason hord <pravus@cpan.org>
