---
abstract: 'Provides an easy-to-use interface for authentication using JA-SIG''s Central Authentication Service'
author:
  - 'jason hord <pravus@cpan.org>'
build_requires:
  Test::MockObject: 0.00
  Test::More: 0.00
distribution_type: module
generated_by: 'Module::Install version 0.75'
license: MIT
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: Authen-CAS-Client
no_index:
  directory:
    - inc
    - t
requires:
  LWP: 0.00
  URI: 0.00
  XML::LibXML: 0.00
  perl: 5.6.1
version: 0.03
